Added: validation service layer "Gateway" and docker files
AndMolPraktikum/java-shareit pull request #4
Opened 2023-06-29 19:06 UTC by AndMolPraktikum

2023-06-29 19:44 UTC, AndMolPraktikum commented
Время на машине выставил UTC
Перед запуском docker compose up выполнил
docker run --rm --privileged alpine hwclock -s

2023-06-30 13:19 UTC, YazykovMikhail requested changes

2023-06-30 13:19 UTC, YazykovMikhail commented on pom.xml
> -<?xml version="1.0" encoding="UTF-8"?>
Зачем удалил мавен? Как теперь программе собираться?
Должен быть общий мавен и для кадого модуля еще свой pom

2023-06-30 13:19 UTC, YazykovMikhail commented on gateway/src/main/java/ru/practicum/shareit/item/ItemControllerGateway.java
> +    @GetMapping  //ToDo Проверить отправку листа
с todo не надо отправлять на ревью)

2023-06-30 13:19 UTC, YazykovMikhail commented on gateway/src/main/java/ru/practicum/shareit/item/ItemControllerGateway.java
> +public class ItemControllerGateway {
ItemController
не надо Gatewat
по названию проекта и так понятно. 
Убери везде

2023-06-30 13:19 UTC, YazykovMikhail commented on gateway/src/main/java/ru/practicum/shareit/request/ItemRequestControllerGateway.java
> +    @GetMapping //ToDo проверить List
Пробегись по всем todo
и что бы их не было)

2023-06-30 13:19 UTC, YazykovMikhail commented on gateway/src/main/java/ru/practicum/shareit/item/ItemControllerGateway.java
> +
А как же контроллер для Booking?

2023-06-30 13:19 UTC, YazykovMikhail commented on gateway/src/main/java/ru/practicum/shareit/user/UserControllerGateway.java
> +
А где папка с ресурсами и файл
application.properties?
ведь каждый сервис будет запускаться на своем порту и иметь свои свойства

2023-06-30 13:19 UTC, YazykovMikhail commented on suppressions.xml
> -<?xml version="1.0" encoding="UTF-8"?>
этот файл тут должен остаться

Так же не хватает docker-compose
и dockerFile для каждого сервиса

2023-06-30 13:27 UTC, AndMolPraktikum commented on gateway/src/main/java/ru/practicum/shareit/request/ItemRequestControllerGateway.java
> +    @GetMapping //ToDo проверить List
Убрал

2023-07-24 07:52 UTC, merged